DLLS= $(MAKDIR)\adminlog.dll \
 $(MAKDIR)\autoattach.dll \
 $(MAKDIR)\autocycle.dll \
 $(MAKDIR)\autoop.dll \
 $(MAKDIR)\autoreply.dll \
 $(MAKDIR)\autovoice.dll \
 $(MAKDIR)\awaynick.dll \
 $(MAKDIR)\awaystore.dll \
 $(MAKDIR)\blockuser.dll \
 $(MAKDIR)\block_motd.dll \
 $(MAKDIR)\bouncedcc.dll \
 $(MAKDIR)\buffextras.dll \
 $(MAKDIR)\cert.dll \
 $(MAKDIR)\certauth.dll \
 $(MAKDIR)\chansaver.dll \
 $(MAKDIR)\clearbufferonmsg.dll \
 $(MAKDIR)\clientnotify.dll \
 $(MAKDIR)\controlpanel.dll \
 $(MAKDIR)\crypt.dll \
 $(MAKDIR)\ctcpflood.dll \
 $(MAKDIR)\dcc.dll \
 $(MAKDIR)\disconkick.dll \
 $(MAKDIR)\fail2ban.dll \
 $(MAKDIR)\flooddetach.dll \
 $(MAKDIR)\identfile.dll \
 $(MAKDIR)\imapauth.dll \
 $(MAKDIR)\keepnick.dll \
 $(MAKDIR)\kickrejoin.dll \
 $(MAKDIR)\lastseen.dll \
 $(MAKDIR)\listsockets.dll \
 $(MAKDIR)\log.dll \
 $(MAKDIR)\missingmotd.dll \
 $(MAKDIR)\modules_online.dll \
 $(MAKDIR)\nickserv.dll \
 $(MAKDIR)\notes.dll \
 $(MAKDIR)\notify_connect.dll \
 $(MAKDIR)\partyline.dll \
 $(MAKDIR)\perform.dll \
 $(MAKDIR)\q.dll \
 $(MAKDIR)\raw.dll \
 $(MAKDIR)\route_replies.dll \
 $(MAKDIR)\sample.dll \
 $(MAKDIR)\sasl.dll \
 $(MAKDIR)\savebuff.dll \
 $(MAKDIR)\schat.dll \
 $(MAKDIR)\send_raw.dll \
 $(MAKDIR)\simple_away.dll \
 $(MAKDIR)\stickychan.dll \
 $(MAKDIR)\watch.dll \
 $(MAKDIR)\webadmin.dll

OBJS= $(MAKDIR)\adminlog.obj \
 $(MAKDIR)\autoattach.obj \
 $(MAKDIR)\autocycle.obj \
 $(MAKDIR)\autoop.obj \
 $(MAKDIR)\autoreply.obj \
 $(MAKDIR)\autovoice.obj \
 $(MAKDIR)\awaynick.obj \
 $(MAKDIR)\awaystore.obj \
 $(MAKDIR)\blockuser.obj \
 $(MAKDIR)\block_motd.obj \
 $(MAKDIR)\bouncedcc.obj \
 $(MAKDIR)\buffextras.obj \
 $(MAKDIR)\cert.obj \
 $(MAKDIR)\certauth.obj \
 $(MAKDIR)\chansaver.obj \
 $(MAKDIR)\clearbufferonmsg.obj \
 $(MAKDIR)\clientnotify.obj \
 $(MAKDIR)\controlpanel.obj \
 $(MAKDIR)\crypt.obj \
 $(MAKDIR)\ctcpflood.obj \
 $(MAKDIR)\dcc.obj \
 $(MAKDIR)\disconkick.obj \
 $(MAKDIR)\fail2ban.obj \
 $(MAKDIR)\flooddetach.obj \
 $(MAKDIR)\identfile.obj \
 $(MAKDIR)\imapauth.obj \
 $(MAKDIR)\keepnick.obj \
 $(MAKDIR)\kickrejoin.obj \
 $(MAKDIR)\lastseen.obj \
 $(MAKDIR)\listsockets.obj \
 $(MAKDIR)\log.obj \
 $(MAKDIR)\missingmotd.obj \
 $(MAKDIR)\modules_online.obj \
 $(MAKDIR)\nickserv.obj \
 $(MAKDIR)\notes.obj \
 $(MAKDIR)\notify_connect.obj \
 $(MAKDIR)\partyline.obj \
 $(MAKDIR)\perform.obj \
 $(MAKDIR)\q.obj \
 $(MAKDIR)\raw.obj \
 $(MAKDIR)\route_replies.obj \
 $(MAKDIR)\sample.obj \
 $(MAKDIR)\sasl.obj \
 $(MAKDIR)\savebuff.obj \
 $(MAKDIR)\schat.obj \
 $(MAKDIR)\send_raw.obj \
 $(MAKDIR)\simple_away.obj \
 $(MAKDIR)\stickychan.obj \
 $(MAKDIR)\watch.obj \
 $(MAKDIR)\webadmin.obj

